name = "aiqbrain-landing"
compatibility_date = "2025-07-23"
main = "index.js"

[vars]
# Core configuration
REDIRECT_DEFAULT = "https://aiqengage.com"
CACHE_TTL = "3600"

# Redirect mappings
REDIRECT_SV = "https://singingfiles.com/show.php?l=0&u=2427730&id=68776"
REDIRECT_VAULT = "https://aiqengage.com/vault"
REDIRECT_START = "https://aiqengage.com/get-started"

# Analytics (optional)
PLAUSIBLE_DOMAIN = "aiqbrain.com"
GA_MEASUREMENT_ID = "G-XXXXXXXXXX"