name = "aiqbrain-landing"
main = "dist/index.js"
compatibility_date = "2025-07-31"
workers_dev = true
usage_model = "bundled"

[build]
command = "npm run build"

[env.production]
name = "aiqbrain-prod"  
workers_dev = false
route = { pattern = "aiqbrain.com/*", zone_name = "aiqbrain.com" }

# ================= ENVIRONMENT VARIABLES =================
[vars]
# ================= CORE REDIRECTS =================
REDIRECT_VAULT = "https://aiqengage.com/vault"
REDIRECT_START = "https://aiqengage.com/get-started" 
REDIRECT_PRIVACY = "https://aiqengage.com/privacy"
REDIRECT_COMPLIANCE = "https://aiqengage.com/compliance"
REDIRECT_TERMS = "https://aiqengage.com/terms"

# ================= CPA OFFER ROTATION =================
# IMPORTANT: Replace these with your actual CPA offers
SV_OFFER_A = "https://your-network.com/offer?id=1001"
SV_OFFER_B = "https://your-network.com/offer?id=1002"
SV_OFFER_C = "https://your-network.com/offer?id=1003"
SV_OFFER_D = "https://your-network.com/offer?id=1004"

# ================= GEO-TARGETED OFFERS =================
# IMPORTANT: Replace with geo-specific offers
GEO_OFFERS_US = "https://your-network.com/us-offer"
GEO_OFFERS_UK = "https://your-network.com/uk-offer"
GEO_OFFERS_DE = "https://your-network.com/de-offer"
GEO_OFFERS_CA = "https://your-network.com/ca-offer"
GEO_OFFERS_AU = "https://your-network.com/au-offer"

# ================= DEVICE-SPECIFIC =================
MOBILE_VAULT = "https://m.aiqengage.com/vault"
MOBILE_START = "https://m.aiqengage.com/start"
DESKTOP_VAULT = "https://aiqengage.com/vault"
DESKTOP_START = "https://aiqengage.com/start"

# ================= TIME-BASED OFFERS =================
# IMPORTANT: Replace with time-specific offers
WEEKEND_OFFER = "https://your-network.com/weekend-offer"
EVENING_OFFER = "https://your-network.com/evening-offer"
Q4_PROMO = "https://your-network.com/holiday-offer"

# ================= SECURITY =================
ALLOWED_COUNTRIES = "US,CA,UK,DE,AU,JP,NZ,FR,IT,ES,NL,SE,NO,DK,FI"
BLOCKED_IPS = "" # Add IPs to block, comma-separated
RATE_LIMIT = "100" # Requests per minute per IP
MAINTENANCE_ENABLED = "false"
MAINTENANCE_MESSAGE = "AIQBrain is currently under maintenance. Please check back soon."

# ================= PERFORMANCE =================
CACHE_TTL = "3600" # 1 hour
EDGE_CACHE_TTL = "14400" # 4 hours
JS_BUNDLE_VERSION = "v1.0.0"

# ================= ANALYTICS =================
# IMPORTANT: Replace with your actual analytics IDs
PLAUSIBLE_DOMAIN = "aiqbrain.com"
GA_MEASUREMENT_ID = "G-XXXXXXXXXX" # Replace with actual ID
GTM_CONTAINER_ID = "GTM-XXXXXX" # Replace with actual ID
FACEBOOK_PIXEL_ID = "1234567890" # Replace with actual ID

# ================= CONVERSION OPTIMIZATION =================
AB_TEST_SPLIT = "0.3,0.3,0.3,0.1" # A/B/C/D weights
EXIT_INTENT_DISCOUNT = "30"
URGENCY_SPOTS_LEFT = "25"
URGENCY_TIMER_HOURS = "24"
CONVERSION_COOLDOWN = "86400" # 24 hours

# ================= API INTEGRATIONS =================
# IMPORTANT: Replace with your actual endpoints
CRM_API_ENDPOINT = "https://crm.aiqbrain.com/api/v3"
PAYMENT_GATEWAY = "https://pay.aiqbrain.com/process"
AFFILIATE_API = "https://affiliates.aiqbrain.com/v2"
WEBHOOK_URL = "https://your-backend.com/webhooks/conversions"

# ================= KV NAMESPACES =================
# IMPORTANT: Create these namespaces and update IDs
# Run: wrangler kv:namespace create "CONVERSION_LOGS" to get the IDs
# Then replace the placeholder IDs below

# Uncomment and replace with actual KV namespace IDs after creation:
# [[kv_namespaces]]
# binding = "CONVERSION_LOGS"
# id = "YOUR_KV_ID_HERE" 
# preview_id = "YOUR_PREVIEW_ID_HERE"

# [[kv_namespaces]]
# binding = "ERROR_LOGS"
# id = "YOUR_KV_ID_HERE"
# preview_id = "YOUR_PREVIEW_ID_HERE"

# [[kv_namespaces]]
# binding = "RATE_LIMITER"
# id = "YOUR_KV_ID_HERE"
# preview_id = "YOUR_PREVIEW_ID_HERE"

# [[kv_namespaces]]
# binding = "USER_SESSIONS"
# id = "YOUR_KV_ID_HERE"
# preview_id = "YOUR_PREVIEW_ID_HERE"

# [[kv_namespaces]]
# binding = "OFFER_HEALTH"
# id = "YOUR_KV_ID_HERE"
# preview_id = "YOUR_PREVIEW_ID_HERE"

# ================= SECRETS =================
# Set these via CLI - DO NOT put values here!
# Run: wrangler secret put SECRET_NAME
# - WEBHOOK_SECRET
# - GA_API_SECRET  
# - SMTP_CREDENTIALS
# - API_KEY
