name = "aiqbrain-landing"
main = "src/worker.js"
compatibility_date = "2025-06-01"

[vars]
OFFERS_PATH = "/data/cloudflare_offers.json"
ALLOWED_HOSTS = "aiqbrain.com"

[[kv_namespaces]]
binding = "BOT_LOG_KV"
id = "YOUR_KV_NAMESPACE_ID"
