name = "aiqbrain-landing"
main = "index.js"
compatibility_date = "2025-07-23"
workers_dev = true
type = "javascript"

[vars]
# Redirects
REDIRECT_VAULT = "https://aiqengage.com/vault"
REDIRECT_START = "https://aiqengage.com/get-started"

# CPA Offers (A/B/C)
SV_OFFER_A = "https://singingfiles.com/show.php?l=0&u=2427730&id=68776"
SV_OFFER_B = "https://singingfiles.com/show.php?l=0&u=2427730&id=68777"
SV_OFFER_C = "https://singingfiles.com/show.php?l=0&u=2427730&id=68778"

# Geo Targeting
GERMAN_OFFER = "https://your-german-cpa-offer.com"
GERMAN_VAULT = "https://your-german-vault.com"

# Device-specific
MOBILE_VAULT = "https://mobile-optimized-vault.com"
MOBILE_START = "https://mobile-onboarding.com"

# Time-based optimization
WEEKEND_OFFER = "https://weekend-special-offer.com"
EVENING_OFFER = "https://evening-boost-offer.com"

# Performance
CACHE_TTL = "3600"
ASSET_CACHE_CONTROL = "public, max-age=31536000, immutable"
EDGE_CACHE_TTL = "14400"

# Analytics / Reserved
PLAUSIBLE_DOMAIN = "aiqbrain.com"
GA_MEASUREMENT_ID = "G-XXXXXXXXXX"
GTM_CONTAINER_ID = "GTM-XXXXXX"
FACEBOOK_PIXEL_ID = "1234567890"

# Conversion Settings
EXIT_INTENT_DISCOUNT = "30"
URGENCY_SPOTS_LEFT = "50"
URGENCY_TIMER_HOURS = "24"
