name = "aiqbrain-landing"
main = "index.js"
compatibility_date = "2025-07-23"
workers_dev = true

[vars]
# Core Configuration
REDIRECT_DEFAULT = "https://aiqengage.com"
CACHE_TTL = "86400"

# Redirect Mappings
REDIRECT_SURVEYVAULT = "https://singingfiles.com/show.php?l=0&u=2427730&id=68776"
REDIRECT_SV = "https://singingfiles.com/show.php?l=0&u=2427730&id=68776"
REDIRECT_VAULT = "https://aiqengage.com/vault"
REDIRECT_START = "https://aiqengage.com/get-started"

# Analytics Configuration
PLAUSIBLE_DOMAIN = "aiqbrain.com"
GA_MEASUREMENT_ID = "G-XXXXXXXXXX"
GTM_CONTAINER_ID = "GTM-XXXXXX"

# Performance
ASSET_CACHE_CONTROL = "public, max-age=31536000, immutable"
EDGE_CACHE_TTL = "14400"
