name = "aiqbrain-landing"
main = "src/worker.js"
compatibility_date = "2025-06-01"

kv_namespaces = [
  { binding = "AIQ_ANALYTICS", id = "xxxxx", preview_id = "xxxxx" },
  { binding = "AIQ_VISITORS", id = "xxxxx", preview_id = "xxxxx" }
]

[vars]
PLAUSIBLE_API_KEY = ""
WEBHOOK_SECRET = ""
WEBHOOK_URL = "https://api.aiqbrain.com/webhooks/events"
GEO_ROUTING_ENABLED = "true"
TIME_ROUTING_ENABLED = "true"
DEVICE_ROUTING_ENABLED = "true"

[env.production]
routes = [
  { pattern = "aiqbrain.com/*", zone_name = "aiqbrain.com" }
]

[env.production.vars]
ENVIRONMENT = "production"
DEBUG_MODE = "false"

[env.staging]
routes = [
  { pattern = "staging.aiqbrain.com/*", zone_name = "aiqbrain.com" }
]

[env.staging.vars]
ENVIRONMENT = "staging"
DEBUG_MODE = "true"
