name = "aiqbrain-landing"
main = "dist/index.js"
compatibility_date = "2025-07-30"
workers_dev = true
usage_model = "bundled"

[build]
command = "npm run build"
upload.format = "modules"
upload.dir = "dist"

[env.production]
name = "aiqbrain-prod"
zone_id = "78ac727a756f49b190a3d68a2d56f407" # Replace with your actual zone ID
route = "aiqbrain.com/*"
workers_dev = false

[vars]
# ================= CORE REDIRECTS =================
REDIRECT_VAULT = "https://aiqengage.com/vault"
REDIRECT_START = "https://aiqengage.com/get-started"
REDIRECT_PRIVACY = "https://aiqengage.com/privacy"
REDIRECT_COMPLIANCE = "https://aiqengage.com/compliance"

# ================= CPA OFFER ROTATION =================
SV_OFFERS_A = "https://singingfiles.com/show.php?l=0&u=2427730&id=68776"
SV_OFFERS_B = "https://singingfiles.com/show.php?l=0&u=2427730&id=68777"
SV_OFFERS_C = "https://singingfiles.com/show.php?l=0&u=2427730&id=68778"
SV_OFFERS_D = "https://singingfiles.com/show.php?l=0&u=2427730&id=68779" # High-converting variant

# ================= GEO-TARGETED OFFERS =================
GEO_OFFERS_US = "https://singingfiles.com/show.php?l=0&u=2427730&id=68831"
GEO_OFFERS_UK = "https://singingfiles.com/show.php?l=0&u=2427730&id=68583"
GEO_OFFERS_DE = "https://your-german-cpa-offer.com"
GEO_OFFERS_CA = "https://singingfiles.com/show.php?l=0&u=2427730&id=68846"
GEO_OFFERS_AU = "https://your-australia-cpa-offer.com"

# ================= DEVICE-SPECIFIC =================
MOBILE_VAULT = "https://m.aiqengage.com/vault"
MOBILE_START = "https://m.aiqengage.com/start"
DESKTOP_VAULT = "https://aiqengage.com/vault"
DESKTOP_START = "https://aiqengage.com/start"

# ================= TIME-BASED OFFERS =================
WEEKEND_OFFER = "https://weekend-special-offer.com"
EVENING_OFFER = "https://evening-boost-offer.com"
Q4_PROMO = "https://q4-special-promo.com" # Seasonal offer

# ================= SECURITY =================
ALLOWED_COUNTRIES = "US,CA,UK,DE,AU,JP,NZ" # Comma-separated
BLOCKED_IPS = "192.168.1.1,10.0.0.1" # Internal/testing IPs
RATE_LIMIT = "1000/60" # 1000 requests per minute
MAINTENANCE_ENABLED = "false" # Flip to "true" for maintenance

# ================= PERFORMANCE =================
CACHE_TTL = "3600" # 1 hour
EDGE_CACHE_TTL = "14400" # 4 hours
JS_BUNDLE_VERSION = "v3.2.1" # Cache busting

# ================= ANALYTICS =================
PLAUSIBLE_DOMAIN = "aiqbrain.com"
GA_MEASUREMENT_ID = "G-XXXXXXXXXX" # Replace with actual ID
GTM_CONTAINER_ID = "GTM-XXXXXX" # Replace with actual ID
FACEBOOK_PIXEL_ID = "1234567890" # Replace with actual ID

# ================= CONVERSION OPTIMIZATION =================
AB_TEST_SPLIT = "0.3,0.3,0.3,0.1" # A/B/C/D weights (must sum to 1)
EXIT_INTENT_DISCOUNT = "30" # Percentage
URGENCY_SPOTS_LEFT = "50" # Initial count
URGENCY_TIMER_HOURS = "24"
CONVERSION_COOLDOWN = "86400" # 24 hours in seconds

# ================= API INTEGRATIONS =================
CRM_API_ENDPOINT = "https://crm.aiqbrain.com/api/v3"
PAYMENT_GATEWAY = "https://pay.aiqbrain.com/process"
AFFILIATE_API = "https://affiliates.aiqbrain.com/v2"

# ================= KV NAMESPACES =================
kv_namespaces = [
  { binding = "CONVERSION_LOGS", id = "3e8a8b8b8b8b8b8b8b8b8b8b8b8b8b8b", preview_id = "3e8a8b8b8b8b8b8b8b8b8b8b8b8b8b8b" },
  { binding = "ERROR_LOGS", id = "4f9a9c9c9c9c9c9c9c9c9c9c9c9c9c9c", preview_id = "4f9a9c9c9c9c9c9c9c9c9c9c9c9c9c9c" }
]

# ================= SECRETS (set via CLI) =================
# Run:
# wrangler secret put WEBHOOK_SECRET
# wrangler secret put WEBHOOK_URL
# wrangler secret put SMTP_CREDENTIALS
