name = "aiqbrain-landing"
main = "src/worker.js"
compatibility_date = "2025-06-01"

[[kv_namespaces]]
binding = "UNLOCK_KV"
id = "245ad1781ade43bcab7b60cf7a8c5934"

[[kv_namespaces]]
binding = "REDIRECT_LOG_KV"
id = "5df78f1513a948959eaf964e9071449e"

[[kv_namespaces]]
binding = "BOT_LOG_KV"
id = "596e08056965435ba928a8086d82df9"

[vars]
UNLOCK_WEBHOOK_URL = "https://hook.us2.make.com/p8nhi2vxwmyrzvw875k4opocqcn2olrv"
