name = "aiqbrain-landing"
main = "src/worker.js"
compatibility_date = "2025-06-01"

[[kv_namespaces]]
binding = "BOT_LOG_KV"
id = "59e608056956435ba9288a0866d82df9"
preview_id = "935398f9f4cc4a10809b8acbcc9a809c"

[vars]
OFFERS_PATH = "/data/cloudflare_offers.json"
ALLOWED_HOSTS = "aiqbrain.com"

US_ANDROID = "https://singingfiles.com/show.php?l=0&u=2427730&id=68831"
US_IOS     = "https://singingfiles.com/show.php?l=0&u=2427730&id=69234"
UK_ANDROID = "https://singingfiles.com/show.php?l=0&u=2427730&id=68583"
CAN_ANDROID= "https://singingfiles.com/show.php?l=0&u=2427730&id=68846"
CAN_IOS    = "https://singingfiles.com/show.php?l=0&u=2427730&id=69339"
FALLBACK_OFFER = "https://singingfiles.com/show.php?l=0&u=2427730&id=68831"

MAKE_WEBHOOK_URL = "https://hook.us2.make.com/xo6kznpoafou41c9d84wjxstg487rbfe"  # TODO: replace with your real Make.com webhook URL
BOT_ASN_DENYLIST = "15169,32934,8075,16509,14618,54113"  # Google, Meta, Microsoft, AWS, Amazon, Fastly
