name: Reddit Post Validator
on: { workflow_dispatch: {} }
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: node .reddit-compliance/post-validator.mjs
        env:
          MIN_DISCLOSURE_TEXT: ${{ secrets.MIN_DISCLOSURE_TEXT }}
