name: Validate Offers

on:
  pull_request:
    paths:
      - "public/data/cloudflare_offers.json"
      - "wrangler.toml"
      - "scripts/validate_offers.mjs"
  push:
    branches: [ "main" ]
    paths:
      - "public/data/cloudflare_offers.json"
      - "wrangler.toml"
      - "scripts/validate_offers.mjs"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Validate cloudflare_offers.json
        env:
          # Optional: override or append to wrangler.toml allow-list
          # ALLOWED_HOSTS: apple.com,play.google.com,apps.apple.com,microsoft.com,wikipedia.org
          NODE_NO_WARNINGS: "1"
        run: node scripts/validate_offers.mjs
